-- Insert mock projects into the database
BEGIN;

INSERT INTO projects (title, slug, category, type, location, year, area, client, design_style, cover_image, description, highlights, scope, is_featured, published)
VALUES 
(
    'M/s Relevantz Technologies',
    'relevantz-technologies',
    'IT & ITES OFFICES',
    'INTERIOR',
    'Chennai, India',
    '2024',
    '60,000 Sq.Ft',
    'Relevantz Technologies Pvt Ltd',
    'Contemporary Corporate',
    'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=1400',
    'A contemporary IT workspace designed to promote collaboration, agility, and employee well-being.',
    ARRAY['Collaborative open office planning', 'Biophilic design elements', 'Energy-efficient lighting', 'Flexible work zones'],
    ARRAY['Interior Design', 'MEP Coordination', 'Turnkey Execution'],
    true,
    true
),
(
    'M/s Emerson Process Management',
    'emerson-process-management',
    'IT & ITES OFFICES',
    'INTERIOR',
    'Chennai, India',
    '2023',
    '45,000 Sq.Ft',
    'Emerson',
    'Global Corporate',
    'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?auto=format&fit=crop&q=80&w=1400',
    'Corporate office interiors reflecting global brand standards and operational efficiency.',
    ARRAY['Brand-aligned interiors', 'Efficient space planning', 'High-performance workstations'],
    ARRAY['Interior Design', 'Project Management'],
    true
),
(
    'M/s OFS Technologies',
    'ofs-technologies',
    'IT & ITES OFFICES',
    'INTERIOR',
    'Bangalore, India',
    '2022',
    '38,000 Sq.Ft',
    'OFS',
    'Modern Tech Office',
    'https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&q=80&w=1400',
    'Technology-driven office interiors supporting high-performance teams.',
    ARRAY['Optimized workstation layouts', 'Collaboration hubs', 'Minimal modern palette'],
    ARRAY['Space Planning', 'Interior Design'],
    false
),
(
    'M/s Forbes Marshall – Regional Office',
    'forbes-marshall',
    'IT & ITES OFFICES',
    'INTERIOR',
    'Chennai, India',
    '2023',
    '25,000 Sq.Ft',
    'Forbes Marshall',
    'Corporate Modern',
    'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&q=80&w=1400',
    'Regional corporate office designed for leadership presence and functional clarity.',
    ARRAY['Executive office planning', 'Brand identity integration'],
    ARRAY['Interior Design', 'Brand Integration'],
    true
),
(
    'M/s Panalpina World Transport',
    'panalpina',
    'IT & ITES OFFICES',
    'INTERIOR',
    'Mumbai, India',
    '2022',
    '28,000 Sq.Ft',
    'Panalpina',
    'Corporate Industrial',
    'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=80&w=1400',
    'Logistics corporate office balancing operations and administration.',
    ARRAY['Functional zoning', 'Durable material palette'],
    ARRAY['Interior Design'],
    false
),
(
    'M/s Al Saraya Corniche Club',
    'al-saraya-club',
    'CLUBS & RESTO BARS',
    'INTERIOR',
    'Chennai, India',
    '2024',
    '18,000 Sq.Ft',
    'Al Saraya',
    'Luxury Contemporary',
    'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=1400',
    'Premium club interiors blending luxury with vibrant social spaces.',
    ARRAY['Mood lighting design', 'High-end material palette'],
    ARRAY['Interior Design', 'Lighting'],
    true
),
(
    'M/s DCP Warehouse',
    'dcp-warehouse',
    'WAREHOUSE & FACTORY BUILDINGS',
    'ARCHITECTURE',
    'Oragadam, India',
    '2023',
    '1,80,000 Sq.Ft',
    'DCP',
    'Industrial Functional',
    'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?auto=format&fit=crop&q=80&w=1400',
    'Large-scale warehouse optimized for logistics and storage efficiency.',
    ARRAY['Efficient vehicular movement', 'Optimized structural spans'],
    ARRAY['Architecture', 'Execution'],
    false
),
(
    'M/s Blaack Forest',
    'blaack-forest',
    'SHOWROOM & RETAIL OUTLETS',
    'INTERIOR',
    'Chennai, India',
    '2024',
    '18,000 Sq.Ft',
    'Blaack Forest',
    'Luxury Contemporary',
    'https://images.unsplash.com/photo-1554995207-c18c203602cb?auto=format&fit=crop&q=80&w=1400',
    'Premium showroom interiors blending luxury with vibrant retail spaces.',
    ARRAY['Mood lighting design', 'High-end material palette'],
    ARRAY['Interior Design', 'Lighting'],
    false
)
ON CONFLICT (slug) DO NOTHING;

COMMIT;
